SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'a%' OR CITY LIKE 'e%' OR CITY LIKE 'i%' OR CITY LIKE 'u%' OR CITY LIKE 'o%';

/*
SELECT DISTINCT city FROM station WHERE city REGEXP "^[aeiou].*";
*/